name: textil_investigation
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  diacritic: ^0.1.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.3
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.2
  go_router: ^14.4.1
  http: ^1.2.2
  intl: ^0.19.0
  material_design_icons_flutter: ^7.0.7296
  motion_tab_bar: ^2.0.4
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/back.png
    - assets/backwithout.png
    - assets/maquinacoser.png
    - assets/imperdible.png
    - .env
